Performance Metrics Overview:

1. Business Metric: A weighted sum of controls normalized between 0 and 1, with the top 20% flagged as critical data quality issues.


2. Anomaly Score: Generated by the model, also normalized, with the top 20% flagged as anomalies.


3. Comparison: Thresholds classify data into comparable groups to evaluate alignment between the business controls and the model.



